Sprint7
ClevertecFrontendLab/YauhenV pull request #5
Opened 2023-03-24 16:33 UTC by YauhenV

2023-03-24 16:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/5-slider-after-1440px.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- test layout burger-menu (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679676440/Sprint%202%20--%20slider%20tests%20--%20test%20layout%20burger-menu%20(failed).png)

2023-03-24 20:02 UTC, Gaurrus requested changes

2023-03-24 20:02 UTC, Gaurrus commented on src/api/requests.ts
> +  data: {
![image](https://user-images.githubusercontent.com/85307211/227627199-6d8adfb0-f020-486d-9210-74b8c8275ed2.png)

фулскрин в карточке "Книга на руках" текст с датой возврата не по дизайну
![image](https://user-images.githubusercontent.com/85307211/227627005-29123b17-e69a-43a6-8282-7f6832c25e07.png)

2023-03-24 22:50 UTC, ValadzkoAliaksei commented on src/api/requests.ts
> +  await axios.delete(`https://strapi.cleverland.by/api/bookings/${data.id}`, {
хосты вынеси, и строки запроса тоже в отдельную переменную. АПИ

2023-03-24 22:50 UTC, ValadzkoAliaksei commented on src/api/requests.ts
> +  })
и ты это везде одно и тоже делаешь? и не лень?)

2023-03-24 22:50 UTC, ValadzkoAliaksei commented on src/components/book-card/book-card.tsx
> +export const BookCard: FC<BookCardProps> = ({
интерфейсы переделать в type

2023-03-24 22:50 UTC, ValadzkoAliaksei commented on src/components/book-card/book-card.tsx
> +        setTitleBook(`${title.slice(0, 70)  }...`);
прикольный способ обрезать title)

2023-03-24 22:50 UTC, ValadzkoAliaksei commented on src/components/change-registration-data/change-registration-data.module.scss
> +$colorRed: #F42C4F;
и ты в каждом файле задаешь эти переменные? и в чем смысл тогда? ведь задать можно совсем разные...

2023-03-24 22:50 UTC, ValadzkoAliaksei commented on src/components/ui/app-layout/app-layout.tsx
> +        || isChangeReviewAlert === true
можно просто проверять на наличие  а не сравнивать явно с true

2023-03-24 22:50 UTC, ValadzkoAliaksei commented on src/pages/profile/profile-page.tsx
> +  const commentsBooks = userData?.comments?.map(comment => comment.bookId)
с селекторами тоже переделай

2023-03-24 22:50 UTC, ValadzkoAliaksei commented on src/pages/profile/profile-page.tsx
> +}
это все можно вынести в константу

2023-03-25 07:19 UTC, YauhenV commented on src/api/requests.ts
> +interface DataTypes {
Запросы отменяются, потому что они реализованы через useEffect и при разработке мы используем StrictMode, из-за этого получаем два рендара страницы и, следовательно, дублирование запросов. Поэтому было реализована отмена первого запроса.

2023-03-25 18:09 UTC, ValadzkoAliaksei commented on src/api/requests.ts
> +    password: string,
![image](https://user-images.githubusercontent.com/61273546/227733955-b448cb82-434c-4761-9c73-209dc81e0c2a.png)
комменты есть, но они не раскрываются(

2023-03-25 18:09 UTC, ValadzkoAliaksei commented on src/api/requests.ts
> +    password: string,
![image](https://user-images.githubusercontent.com/61273546/227734036-2b9b17e1-a8b6-4599-ad8d-ca016486c82e.png)
не могу комментарий отправить(

2023-03-25 18:09 UTC, ValadzkoAliaksei commented on src/api/requests.ts
> +    username: string,
![image](https://user-images.githubusercontent.com/61273546/227734071-0a1d702c-8a69-4cd4-8e4b-7133e8f92195.png)
Поля должны быть предзаполнены данными которые пришли с пользователем

2023-03-25 18:09 UTC, ValadzkoAliaksei commented on src/api/requests.ts
> +    lastName: string,
![image](https://user-images.githubusercontent.com/61273546/227734102-1aa0f24a-c83f-4e36-8857-640a56e7e2a2.png)
не работает переход на книгу ни там, ни там

2023-03-25 18:09 UTC, ValadzkoAliaksei commented on src/api/requests.ts
> +    passwordConfirmation: string,
![image](https://user-images.githubusercontent.com/61273546/227734152-25b44106-93b9-403c-b12e-7e4c7dbeba55.png)
при изменении комментария не подтягиваются данные старого комментария. и вновь не передается пользователь и падает ошибка

2023-03-25 18:09 UTC, ValadzkoAliaksei commented on src/api/requests.ts
> +    selectedDateFormat: Date,
![image](https://user-images.githubusercontent.com/61273546/227734203-352cf0a2-1eda-470a-8b68-e6817d5ff64c.png)
если нет фотки в комментах, то должен быть котик

2023-03-25 18:11 UTC, ValadzkoAliaksei commented on src/api/requests.ts
> +    text: string,
![image](https://user-images.githubusercontent.com/61273546/227734287-76e5b414-e902-48fa-82a6-86c2ed0c5218.png)
бургер меню не открывается вообще(

2023-03-26 22:09 UTC, YauhenV commented on src/pages/profile/profile-page.tsx
> +  const commentsBooks = userData?.comments?.map(comment => comment.bookId)
данные селекторы я использую для обновления страницы, при появления в них информации. Если убрать в createSelector, то они будут передаваться одним массивом.

2023-03-27 05:24 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- authorization -- validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauhenV/1679894644/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20validation%20(failed).png)

2023-03-27 09:16 UTC, ValadzkoAliaksei approved these changes

2023-03-27 09:59 UTC, Gaurrus approved these changes

2023-03-27 10:00 UTC, merged